wind:
  wx:
    appid: wx87bf5644ba49df45
    secret: 6f81b81da3dfae55fd958d21a2acf41e
server:
  port: 8089
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3308/wind?useUnicode=true&characterEncoding=utf8
      username: root
      password: Sh.7947..
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379

