server:
  port: 8089
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3308/wind?useUnicode=true&characterEncoding=utf8
      username: root
      password: Sh.7947..
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
